name: Deploy React App to GitHub Pages

# This workflow deploys a React app to GitHub Pages whenever there is a push to the main branch or when manually triggered.
on: 
  workflow_dispatch:
    inputs:
      DEPLOY_TAG_ONLY_UAT_RC:
        description: 'Deploy only if the tag is UAT or RC'
        required: false
        default: false
        type: boolean

run-name: "TAG: ${{ vars._IMAGE_TAG_UAT_RC }} - TAG REDEPLOY: ${{ github.event.inputs.DEPLOY_TAG_ONLY_UAT_RC }}"

jobs:
  build_1:
    if: ${{ github.event.inputs.DEPLOY_TAG_ONLY_UAT_RC == 'false' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup environment
        run: |
          echo "Setting up environment..."
          npm --version
          node --version
          export PATH=$PATH:/usr/share/base-completion/completion/