name: Deploy React App to GitHub Pages

# This workflow deploys a React app to GitHub Pages whenever there is a push to the main branch or when manually triggered.
on: [push, workflow_dispatch]


jobs:
  build_1:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: print node version
        run: node -v
      - name: Install dependencies
        run: npm install